- hosts: all
  gather_facts: no
  tasks:
   - name: Change the hostname to windows-desktop
     ansible.windows.win_hostname:
       name: windows-desktop
     register: res

   - win_reboot:
     when: res.reboot_required

   - win_domain_membership:
       dns_domain_name: {{ domain_name }}
       domain_admin_user: {{ domain_admin }}
       domain_admin_password: {{ domain_pass }}
       state: domain
     register: domain_state

   - win_reboot:
     when: domain_state.reboot_required

